import BASE_CONTRACT_ABI from "./base.json";
import CONFIG_CONTRACT_ABI from "./config.json";
import REWARD_DISPATCHER_CONTRACT_ABI from "./RewardDispatcher.json";
import SVMETIS_CONTRACT_ABI from "./sveMETIS.json";
import VEMETIS_CONTRACT_ABI from "./veMETIS.json";
import VEMETIS_MINTER_CONTRACT_ABI from "./veMetisMinter.json";

export {
  BASE_CONTRACT_ABI,
  CONFIG_CONTRACT_ABI,
  REWARD_DISPATCHER_CONTRACT_ABI,
  SVMETIS_CONTRACT_ABI,
  VEMETIS_CONTRACT_ABI,
  VEMETIS_MINTER_CONTRACT_ABI
};
