name: deploy stage

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploy velix-frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_STAGE_HOST}}
          key: ${{secrets.SSH_STAGE_KEY}}
          username: ${{secrets.SSH_STAGE_USER_NAME}}
          script_stop: true
          script: |
            cd velix-frontend
            git checkout staging
            git fetch --all
            git pull
            sh .github/workflows/scripts/deploy-stage.sh
