name: release-please

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: dev

      - name: Get release tag
        run: |
          echo RELEASE_TAG=${ steps.release.outputs.releases_created } >> $GITHUB_ENV

      - name: Use release tag
        run: echo "The release tag is ${{ env.RELEASE_TAG }}"
