name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.1"

      - name: Check Node.js version
        run: node -v


      - name: Install dependencies
        run: npm install

      - name: Run release
        run: | 
          echo "token is ${{ secrets.GITHUB_TOKEN }}"
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release tag
        run: echo "The release tag is ${{ env.NEXT_RELEASE_VERSION }}"
