name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - name: Set credentials of the current actor
        uses: ./.github/actions/setup-git-credentials
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Node.js version
        run: node -v

      - name: Install and cache pnpm
        uses: ./.github/actions/install-and-cache-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        if: env.NEXT_RELEASE_VERSION != ''
        run: |
         branch_name="releases/${{ env.NEXT_RELEASE_VERSION }}"
         git checkout -b $branch_name
         git push origin $branch_name
